# Generated by Django 4.2.1 on 2023-05-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkdispenser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dispense_seconds_per_unit',
            field=models.FloatField(help_text='Seconds per ml'),
        ),
    ]
